### ISSUE TITLE
how to inject service in symfony 4?

### ISSUE THREAD

**Issue by newbie78** [gpslab/geoip2#16]
Hi!

I need to inject the service into the controller method like this:
```
namespace App\Controller;

use GeoIp2\Database\Reader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ApiController extends AbstractController
{

  public function someAction(Reader $reader)
  {
    dd($reader);
  }
}
```

but i'm have this error:
```
"Cannot autowire argument $reader of \"App\\Controller\\ApiController::someAction()\": it references class \"GeoIp2\\Database\\Reader\" but no such service exists. You should maybe alias this class to the existing \"geoip2.reader\" service."
```

is it possible to do it somehow?

thanx

**Comment by peter-gribanov** [comment]
You can declare alias for `geoip2.reader` service
```yml
services:
    GeoIp2\Database\Reader:
        alias: 'geoip2.reader'
        public: true
```
