### ISSUE TITLE
Unrecognized option "path" under "gpslab_geoip"

### ISSUE THREAD

**Issue by Mecanik** [gpslab/geoip2#77]
I've just started to configure your package, and it seems you cannot configure the _path_ as per the documentation:

```
In ArrayNode.php line 314:
  Unrecognized option "path" under "gpslab_geoip". Available options are "databases", "default_database", "license", "locales".
```

Please update the documentation to inform people where to put the _path_ key:

```
gpslab_geoip:
    path: '%kernel.project_dir%/var/GeoLite2-City.mmdb'
```

To:

```
databases:
   city:
       edition: 'GeoLite2-City'
       path: '%kernel.project_dir%/var/GeoLite2-City.mmdb'
```

Thanks

**Comment by peter-gribanov** [comment]
You cannot register the database without specifying the `edition` and `license`.

```yaml
gpslab_geoip:
    license: 'XXXXXXXXXXXXXXXX'
    edition: 'GeoLite2-City'
    path: '%kernel.project_dir%/var/GeoLite2-City.mmdb'
```
