### ISSUE TITLE
Usage of ASN database

### ISSUE THREAD

**Issue by henri9813** [gpslab/geoip2#8]
Hello,

How can i use ASN database with your bundle ? 

Best regards

**Comment by peter-gribanov** [comment]
This bundle only registers services of [maxmind/GeoIP2-php](https://github.com/maxmind/GeoIP2-php).
If maxmind/GeoIP2-php supports ASN (i think it does), then you can use it with this bundle.

You can try with this config:
```yml
gpslab_geoip:
    cache: '%kernel.cache_dir%/GeoLite2-ASN.mmdb'
    url: 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz'
```

**Comment by henri9813** [comment]
Yes it support it,

So, i can't read multiple mmdb files ?

**Comment by peter-gribanov** [comment]
> So, i can't read multiple mmdb files ?

Yes. Currently, the bundle does not allow working simultaneously with several database files.

You can independently register a separate service for ASN database.

```yml
services:
    geoip2.reader.asn:
        class: GeoIp2\Database\Reader
        arguments: [ '%kernel.cache_dir%/GeoLite2-ASN.mmdb', '%geoip2.locales%' ]
        public: true
```

**Comment by henri9813** [comment]
Okay, 

Thanks for your reply ! :+1:  :1st_place_medal:

**Comment by peter-gribanov** [comment]
Now you can use multiple GeoIP databases in one application. Need update configuration file.

```yml
gpslab_geoip:
    databases:
        default:
            license: 'XXXXXXXXXXXXXXXX'
            edition: 'GeoLite2-City'
        asn:
            license: 'XXXXXXXXXXXXXXXX'
            edition: 'GeoLite2-ASN'
```

Using in application:

```php
// get a GeoIP2 reader for City database
$default_reader = $this->get('geoip2.database.default_reader');
// or
//$default_reader = $this->get(Reader::class);
// or
//$default_reader = $this->get('geoip2.reader');

// get a GeoIP2 reader for ASN database
$asn_reader = $this->get('geoip2.database.asn_reader');
```

See [README](https://github.com/gpslab/geoip2#multiple-databases) file for more detals.
