### ISSUE TITLE
Update will throw an UnexpectedValueException

### ISSUE THREAD

**Issue by arhonik** [gpslab/geoip2#86]
3.4.47 Symfony version
Update will throw an UnexpectedValueException In MaxMindDownloader.php line 88:
`Cannot decompress zip-based archives with whole-archive compression`
Config:
```
gpslab_geoip:
    license: 'xxx'
    locales: [ 'en' ]
    default_database: 'city'
    databases:
        asn:
            edition: 'GeoLite2-ASN'
            url: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=xxx&suffix=zip'
            path: '%kernel.project_dir%/var/GeoLite2-ASN.mmdb'
        city:
            edition: 'GeoLite2-City'
            url: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City-CSV&license_key=xxx&suffix=zip'
            path: '%kernel.project_dir%/var/GeoLite2-City.mmdb'
        country:
            edition: 'GeoLite2-Country'
            url: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=xxx&suffix=zip'
            path: '%kernel.project_dir%/var/GeoLite2-Country.mmdb'
```
Command:
 `php bin/console geoip2:update asn -vvv`
 
zlib:
```
ZLib Support => enabled
Stream Wrapper => compress.zlib://
Stream Filter => zlib.inflate, zlib.deflate
Compiled Version => 1.2.11
Linked Version => 1.2.11
```

Phar:
```
Phar: PHP Archive support => enabled
Phar API version => 1.1.1
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
gzip compression => enabled
bzip2 compression => disabled (install ext/bz2)
Native OpenSSL support => enabled
```

**Comment by peter-gribanov** [comment]
Please try use suffix `tar.gz`
```yaml
gpslab_geoip:
    databases:
        asn:
            edition: 'GeoLite2-ASN'
            url: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=xxx&suffix=tar.gz'
            path: '%kernel.project_dir%/var/GeoLite2-ASN.mmdb'
```
